[DEFAULT]
BOT_TOKEN = 8797319444:AAEUdVFduTR2nmqImEvyIgQBne6uMmvQyRY
CHAT_ID = -1002316820524

[HOSTS]
Aii-SR-SMS-Stu-Card-01Kids=10.17.1.24
Aii-SR-SMS-Stu-Card-02Adults=10.17.1.23
Aii-SR-Staff-TIO=10.17.1.11